version: '3'

services:
  angular-app:
    container_name: app-front
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    networks:
      - app-network


networks:
  app-network:
    name: back_app-network
    external: true
